### ISSUE TITLE
geojson-to-svg: command not found

### ISSUE THREAD

**Issue by likymm** [derhuerst/geojson-to-svg-cli#4]
after cloning I ran:
$ npm install
$ cat example.geo.json | geojson-to-svg -p lambert > example.svg

and I'm getting:
bash: geojson-to-svg: command not found

and it generated example.svg with no content. please help. thanks!

**Comment by derhuerst** [comment]
If you clone the project, run it via `./cli.js` (e.g. `cat example.geo.json | ./cli.js -p lambert > example.svg`). Otherwise, if you have installed it globally using `npm install -g geojson-to-svg-cli`, you can just run as described in the readme.

In 19328bd4411b5ebbca51407474aa9e1b253d68e2, I have updated the instructions to be clearer.

**Comment by derhuerst** [comment]
Please reopen this issue if this didn't solve your problem.
